name: Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question
      placeholder: Please describe your question in detail
    validations:
      required: true